# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class WaterConsume(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ts: str=None, water_consume: float=None):  # noqa: E501
        """WaterConsume - a model defined in Swagger

        :param ts: The ts of this WaterConsume.  # noqa: E501
        :type ts: str
        :param water_consume: The water_consume of this WaterConsume.  # noqa: E501
        :type water_consume: float
        """
        self.swagger_types = {
            'ts': str,
            'water_consume': float
        }

        self.attribute_map = {
            'ts': 'ts',
            'water_consume': 'waterConsume'
        }
        self._ts = ts
        self._water_consume = water_consume

    @classmethod
    def from_dict(cls, dikt) -> 'WaterConsume':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WaterConsume of this WaterConsume.  # noqa: E501
        :rtype: WaterConsume
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ts(self) -> str:
        """Gets the ts of this WaterConsume.


        :return: The ts of this WaterConsume.
        :rtype: str
        """
        return self._ts

    @ts.setter
    def ts(self, ts: str):
        """Sets the ts of this WaterConsume.


        :param ts: The ts of this WaterConsume.
        :type ts: str
        """

        self._ts = ts

    @property
    def water_consume(self) -> float:
        """Gets the water_consume of this WaterConsume.

        water consuming (ml per day)  # noqa: E501

        :return: The water_consume of this WaterConsume.
        :rtype: float
        """
        return self._water_consume

    @water_consume.setter
    def water_consume(self, water_consume: float):
        """Sets the water_consume of this WaterConsume.

        water consuming (ml per day)  # noqa: E501

        :param water_consume: The water_consume of this WaterConsume.
        :type water_consume: float
        """

        self._water_consume = water_consume
